"""upd

Revision ID: 1cb683e7fe8a
Revises: 73ffda037b31
Create Date: 2023-02-24 14:11:34.090739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb683e7fe8a'
down_revision = '73ffda037b31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
