"""upd

Revision ID: 224a3edd3512
Revises: 0f5ce5b85bb6
Create Date: 2023-02-24 17:37:46.474914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224a3edd3512'
down_revision = '0f5ce5b85bb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
