"""upd

Revision ID: 30af2ce81688
Revises: eee789a73089
Create Date: 2023-02-26 14:42:46.198806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30af2ce81688'
down_revision = 'eee789a73089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
