"""upd

Revision ID: 3d280096e447
Revises: ec5d65ca4c8e
Create Date: 2023-02-24 14:04:22.333545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d280096e447'
down_revision = 'ec5d65ca4c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_created_by_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_modified_by_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_modified_by_fkey', 'users', 'users', ['modified_by'], ['id'])
    op.create_foreign_key('users_created_by_fkey', 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
