"""test_6

Revision ID: 48463ecb9d1e
Revises: 486482c087c1
Create Date: 2023-02-26 15:30:02.993348

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '48463ecb9d1e'
down_revision = '486482c087c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
