"""uererd

Revision ID: 497fd07dad44
Revises: b6c7cdca736c
Create Date: 2023-02-26 15:07:18.799885

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '497fd07dad44'
down_revision = 'b6c7cdca736c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # get metadata from current connection
    meta = sa.MetaData()

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('users',), bind=op.get_bind())

    # define table representation
    some_table_tbl = sa.Table('users', meta)

    t = op.execute("INSERT INTO users VALUES (username, password_hashed, role) ('admin', 'admind', 'admin') ")
    print(t)

    # insert records
    # op.bulk_insert(
    #     some_table_tbl,
    #     [
    #         {
    #                        'username': os.environ.get('ADMIN_NAME'),
    #                        'password_hashed': os.environ.get('ADMIN_PASSWORD'),
    #                        'role': 'admin'
    #                    },
    #     ]
    # )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
