"""upd

Revision ID: 59bfb5f8ac16
Revises: a8171610d81a
Create Date: 2023-02-24 17:26:30.956504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bfb5f8ac16'
down_revision = 'a8171610d81a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
