"""upd1

Revision ID: 68cf0feb24b3
Revises: b5147755791d
Create Date: 2023-02-26 15:06:05.213500

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '68cf0feb24b3'
down_revision = 'b5147755791d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # get metadata from current connection
    meta = sa.MetaData()

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('users',), bind=op.get_bind())

    # define table representation
    some_table_tbl = sa.Table('users', meta)

    # insert records
    op.bulk_insert(
        some_table_tbl,
        [
            {
                           'username': os.environ.get('ADMIN_NAME'),
                           'password_hashed': os.environ.get('ADMIN_PASSWORD'),
                           'role': 'admin'
                       },
        ]
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
