"""upd

Revision ID: 69ce1cee8e66
Revises: a59ce2578792
Create Date: 2023-02-24 17:46:19.034777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ce1cee8e66'
down_revision = 'a59ce2578792'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
