"""upd

Revision ID: 73ffda037b31
Revises: 6feeff933519
Create Date: 2023-02-24 14:10:28.721209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ffda037b31'
down_revision = '6feeff933519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
