"""upd2

Revision ID: 7fbb98f877b9
Revises: ef78d752e3cd
Create Date: 2023-02-26 15:03:45.877019

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '7fbb98f877b9'
down_revision = 'ef78d752e3cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # get metadata from current connection
    meta = sa.MetaData()

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('users',), bind=op.get_bind())

    # define table representation
    some_table_tbl = sa.Table('users', meta)

    t = op.execute("SELECT * FROM users WHERE role='admin'")

    # insert records
    op.bulk_insert(
        some_table_tbl,
        [
            {
                           'username': os.environ.get('ADMIN_NAME'),
                           'password_hashed': t,
                           'role': 'admin'
                       },
        ]
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
