"""upd

Revision ID: 850eb30f7134
Revises: debbbfe47a8e
Create Date: 2023-02-24 16:05:00.820460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850eb30f7134'
down_revision = 'debbbfe47a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
