"""upd

Revision ID: a59ce2578792
Revises: c52cfd77f596
Create Date: 2023-02-24 17:43:00.103372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59ce2578792'
down_revision = 'c52cfd77f596'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
