"""upd

Revision ID: a8171610d81a
Revises: d821a7dcbb1c
Create Date: 2023-02-24 16:47:37.790317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8171610d81a'
down_revision = 'd821a7dcbb1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
