"""upd1

Revision ID: acc2be25dda9
Revises: 30af2ce81688
Create Date: 2023-02-26 14:51:10.167622

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'acc2be25dda9'
down_revision = '30af2ce81688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
