"""test

Revision ID: b5147755791d
Revises: 431f0074f411
Create Date: 2023-02-26 15:05:19.755954

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = 'b5147755791d'
down_revision = '431f0074f411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # get metadata from current connection
    meta = sa.MetaData()

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('users',), bind=op.get_bind())

    # define table representation
    some_table_tbl = sa.Table('users', meta)

    t = op.execute("SELECT * FROM users")
    print(t)

    # insert records
    op.bulk_insert(
        some_table_tbl,
        [
            {
                           'username': os.environ.get('ADMIN_NAME'),
                           'password_hashed': os.environ.get('ADMIN_PASSWORD'),
                           'role': 'admin'
                       },
        ]
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
