"""Add products, tanks, operations, users

Revision ID: b84d8539bc68
Revises: 
Create Date: 2023-02-23 13:25:06.580842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84d8539bc68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hashed', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_modified_by'), 'products', ['modified_by'], unique=False)
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('max_capacity', sa.Float(), nullable=True),
    sa.Column('current_capacity', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanks_created_by'), 'tanks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tanks_modified_by'), 'tanks', ['modified_by'], unique=False)
    op.create_index(op.f('ix_tanks_product_id'), 'tanks', ['product_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_created_by'), 'operations', ['created_by'], unique=False)
    op.create_index(op.f('ix_operations_modified_by'), 'operations', ['modified_by'], unique=False)
    op.create_index(op.f('ix_operations_product_id'), 'operations', ['product_id'], unique=False)
    op.create_index(op.f('ix_operations_tank_id'), 'operations', ['tank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_tank_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_product_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_modified_by'), table_name='operations')
    op.drop_index(op.f('ix_operations_created_by'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_tanks_product_id'), table_name='tanks')
    op.drop_index(op.f('ix_tanks_modified_by'), table_name='tanks')
    op.drop_index(op.f('ix_tanks_created_by'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_index(op.f('ix_products_modified_by'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###
