"""upd

Revision ID: c52cfd77f596
Revises: 224a3edd3512
Create Date: 2023-02-24 17:41:25.177748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52cfd77f596'
down_revision = '224a3edd3512'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
