"""upd

Revision ID: cb615717c632
Revises: 59bfb5f8ac16
Create Date: 2023-02-24 17:32:24.551707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb615717c632'
down_revision = '59bfb5f8ac16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
