"""upd

Revision ID: d821a7dcbb1c
Revises: 850eb30f7134
Create Date: 2023-02-24 16:11:19.002745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd821a7dcbb1c'
down_revision = '850eb30f7134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
