"""upd

Revision ID: debbbfe47a8e
Revises: 1cb683e7fe8a
Create Date: 2023-02-24 15:57:01.146374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debbbfe47a8e'
down_revision = '1cb683e7fe8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
