"""qwe

Revision ID: e88d60701902
Revises: d8cc90b9e9dc
Create Date: 2023-02-26 15:21:43.115498

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = 'e88d60701902'
down_revision = 'd8cc90b9e9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # get metadata from current connection
    meta = sa.MetaData()

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('users',), bind=op.get_bind())

    # define table representation
    some_table_tbl = sa.Table('users', meta)

    con = op.get_bind()
    results = con.execute(sa.text("SELECT id FROM users where role='adsdas'"))
    print(results)

    # insert records
    # op.bulk_insert(
    #     some_table_tbl,
    #     [
    #         {
    #                        'username': os.environ.get('ADMIN_NAME'),
    #                        'password_hashed': os.environ.get('ADMIN_PASSWORD'),
    #                        'role': 'admin'
    #                    },
    #     ]
    # )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
