"""upd

Revision ID: ec5d65ca4c8e
Revises: b84d8539bc68
Create Date: 2023-02-24 13:52:32.744567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5d65ca4c8e'
down_revision = 'b84d8539bc68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tanks_created_by', table_name='tanks')
    op.drop_index('ix_tanks_modified_by', table_name='tanks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tanks_modified_by', 'tanks', ['modified_by'], unique=False)
    op.create_index('ix_tanks_created_by', 'tanks', ['created_by'], unique=False)
    # ### end Alembic commands ###
