"""upd

Revision ID: eee789a73089
Revises: b5a7356bcb91
Create Date: 2023-02-26 14:39:51.101653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee789a73089'
down_revision = 'b5a7356bcb91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
